### ISSUE TITLE
Any idea Connection refused when RUN demo ？

### ISSUE THREAD

**Issue by butterl** [liuqingli/CCLearner#1]
Hi， 
Thanks for sharing this project, I'm flowing the demo and got error when connecting to database with 
```
cclearner@ubuntu:~/Desktop/CCLearner/Run$ java -jar CCLearner_Feature.jar
START!!
Exception in thread "main" org.postgresql.util.PSQLException: Connection to localhost:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:252)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:215)
        at org.postgresql.Driver.makeConnection(Driver.java:406)
        at org.postgresql.Driver.connect(Driver.java:274)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at vt.cs.CCLearner_Feature.main(CCLearner_Feature.java:94)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.postgresql.core.PGStream.<init>(PGStream.java:64)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:133)
        ... 7 more
```

I  tried  with below test, seems the database login is OK， but  I'm not sure if I missed something 
```
cclearner@ubuntu:~/Desktop/CCLearner/Run$ psql -h localhost -U cclearner -d postgres
Password for user cclearner:
psql (10.10 (Ubuntu 10.10-0ubuntu0.18.04.1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=#

```

**Comment by butterl** [comment]
Problem solved by


1. mkdir output  in the root dir
2. change port config to ``` postgreSQL.conn=jdbc:postgresql://localhost:5432/postgres```
